### ISSUE TITLE
Proposal: Integrate ORM for MySQL

### ISSUE THREAD

**Issue by francescobianco** [akiyamaSM/chibi#1]
I'm so sorry to disturb you, I would kindly ask you if you could test this library in your project! 
https://github.com/javanile/moldable
With the purpose of knowing my project and understanding if it can be integrated into yours!
To thank you for your availability I am observing your project and giving a star

Install via composer
```
composer require javanile/moldable
```

I ask you if we can help each other

**Comment by akiyamaSM** [comment]
Once I'll reach to that point I'll try to integrate, it looks great! Great work!

**Comment by akiyamaSM** [comment]
Hello @francescobianco I couldn't integrate it with the framework.
I get the following error

Moldable database error, database connection not found in method '->error()' called at C:\wamp\www\test_orm\vendor\javanile\moldable\src\Model\SchemaApi.php on line 176

**Comment by francescobianco** [comment]
@akiyamaSM can you show me the boot code? Have u connent a database with user and pass?

**Comment by akiyamaSM** [comment]
@francescobianco look I'll make a repo whith a clone of the mini framework and u configure it? is it ok for u?

**Comment by francescobianco** [comment]
Perfect!!!!

Il 16 Ott 2017 10:12, "Inani El Houssain" <notifications@github.com> ha
scritto:

**Comment by akiyamaSM** [comment]
@francescobianco check out the link https://github.com/akiyamaSM/chibi-orm

**Comment by francescobianco** [comment]
@akiyamaSM can you give me permission to write on https://github.com/akiyamaSM/chibi-orm
?

**Comment by akiyamaSM** [comment]
just clone it, make it work and make a PR.
